apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-spot-cluster
  region: us-east-1

managedNodeGroups: # this is also completely managed by AWS
  - name: spot
    instanceType: m5.large
    # your K8 node can be anytime taken back by AWS
    spot: true
    availabilityZones: # ebs static provisioning
    - us-east-1a # there is a reason to select one availablity zone for all nodes.
    desiredCapacity: 3
    ssh:
      publicKeyName: kubernetes # replace this with your keypair exists in AWS.